// Generated by CoffeeScript 1.9.2
(function() {
  var force, height, svg, width;

  width = window.innerWidth;

  height = window.innerHeight;

  svg = d3.select('body').append('svg').attr('width', width).attr('height', height);

  force = d3.layout.force().gravity(0.2).distance(50).charge(-200).linkStrength(0.9).size([width, height]);

  d3.json('graph.json', function(error, graph) {
    var fillColor, link, node, r;
    force.nodes(graph.nodes).links(graph.links).start();
    link = svg.selectAll('.link').data(graph.links).enter().append('line').attr('class', 'link');
    node = svg.selectAll('.node').data(graph.nodes).enter().append('g').attr('class', 'node');
    r = function(d) {
      if (d.Shape === "BIG_Circle") {
        return 30;
      } else {
        return 10;
      }
    };
    fillColor = function(d) {
      if (d.Shape === "BIG_Circle") {
        return 'white';
      }
    };
    node.append('circle').attr('class', function(d) {
      return d.Class;
    }).style('stroke', 'white').style('stroke-width', 1).style('fill', fillColor).attr('r', r).call(force.drag);
    node.append('text').attr('text-anchor', 'middle').attr('alignment-baseline', 'middle').attr('word-break', 'break-all').style('fill', 'black').text(function(d) {
      return d.Name;
    });
    node.on('');
    return force.on('tick', function() {
      link.attr('x1', function(d) {
        return d.source.x;
      }).attr('y1', function(d) {
        return d.source.y;
      }).attr('x2', function(d) {
        return d.target.x;
      }).attr('y2', function(d) {
        return d.target.y;
      });
      return node.attr('transform', function(d) {
        return 'translate(' + d.x + ',' + d.y + ')';
      });
    });
  });

}).call(this);

//# sourceMappingURL=myscript.js.map
